config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :users
      resources :posts
      resources :tags
      resources :sessions
      resources :registrations
    end
  end
end

app/views/layouts/_header.html.erb
  <div uk-sticky="cls-active: uk-navbar-sticky;">
    <div uk-sticky="sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky">
      <nav class="uk-background-primary uk-light" uk-navbar>
        <div class="uk-navbar-left">
          <ul class="uk-navbar-nav">
            <li class="uk-active"><%= link_to 'Home', root_path %></a></li>
            <li>
              <a href="/posts">Posts</a>
              <div class="uk-navbar-dropdown">
                <ul class="uk-nav uk-navbar-dropdown-nav">
                  <li class="uk-active"><a href="/posts/new">New posts</a></li>
                  <li><a href="#">Item</a></li>
                  <li><a href="#">Item</a></li>
                </ul>
              </div>
            </li>
            <li><a href="#">Item</a></li>
          </ul>
        </div>
        <div class="uk-navbar-right">
          <ul class="uk-navbar-nav">
            <% if current_user %>
              <li class="uk-active">
                <a href="#">User</a>
                <div class="uk-navbar-dropdown">
                  <ul class="uk-nav uk-navbar-dropdown-nav">
                    <li><%= link_to "Edit profile", edit_user_path(current_user.id) %></li>
                    <li><%= link_to "Sign out", users_destroy_sessions_path, method: :delete %><li>
                  </ul>
                </div>
              </li>
            <% else %>
              <li><%= link_to "Sign up", sign_up_users_path %></li>
              <li><%= link_to "Sign in", sessions_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DatBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.6.19/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.6.19/dist/js/uikit-icons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/min/dropzone.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/min/dropzone.min.css" />
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="uk-container uk-container-large">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <script>
      <% if flash[:success].present? %>
        UIkit.notification({message: "<span uk-icon=\"icon: check\"></span> <%= flash[:success] %>",
          pos: "top-right", status:"success"})
      <% end %>
      <% if flash[:danger].present? %>
        UIkit.notification({message: "<span uk-icon=\"icon: close\"></span> <%= flash[:danger] %>",
          pos: "top-right", status:"danger"})
      <% end %>
    </script>
  </body>
</html>